<?php

return array(

	/*
	|--------------------------------------------------------------------------
	| FlatTurtle ID
	|--------------------------------------------------------------------------
	*/

	'id' => 'thepassport',


	/*
	|--------------------------------------------------------------------------
	| Content Directory
	|--------------------------------------------------------------------------
	*/

	'directory' => 'content',


	/*
	|--------------------------------------------------------------------------
	| Logo
	|--------------------------------------------------------------------------
	*/

	'logo' => 'images/logo.jpg',


	/*
	|--------------------------------------------------------------------------
	| Carousel
	|--------------------------------------------------------------------------
	|
	| Top image slideshow configuration. Default carousel height is 600px.
	|
	*/

	'carousel_height' => '600px',


	/*
	|--------------------------------------------------------------------------
	| FlatTurtle map
	|--------------------------------------------------------------------------
	|
	| Enable or disable the FlatTurtle map at the bottom of the page. Default
	| map height is 450px.
	|
	*/

	'map' => true,
	'map_height' => '450px',


	/*
	|--------------------------------------------------------------------------
	| Mailchimp Form URL
	|--------------------------------------------------------------------------
	|
	| The Form URL can be found in the embedded form code generated by mailchimp.
	| Leave empty to disable mailchimp signup.
	|
	*/

	'mailchimp' => null,


	/*
	|--------------------------------------------------------------------------
	| Google Analytics Account Code
	|--------------------------------------------------------------------------
	|
	| Leave empty to disable google analytics.
	|
	*/

	'analytics' => null,


	/*
	|--------------------------------------------------------------------------
	| Social Media
	|--------------------------------------------------------------------------
	|
	| The key defines the icon that is used and the value is the corresponding
	| url. You can check the available icons at:
	| 	http://fortawesome.github.io/Font-Awesome/icons/#brand
	|
	| Example:
	|	'facebook' => 'https://www.facebook.com/pages/FlatTurtle/451854318217554'
	|
	*/

	'social' => array(
	)

);
